Pull Request for #11: Prepare EventstudyFHS (#12)
* #11 Add FHS functions

* #11 Add FHS examples

* #11 Fix examples in FHS documentation

* #11 Allow FHS lm output

* #11 Fix clustering argument

* #11 Fix to TestLinear for proxyIV

* #11 Remove CI & Supt for both normalized k and proxyiv k

* #11 Add FHS tests for `PrepareModelFormula`

* #11 Adjust regression output to match stata

* #11 Fix typo and make keyboard shortcuts clearer

* #11 Disable non-cluster robust pathway when FE=TRUE

* #11 Implement default instrument selection

* #11 Add FHS example for EventStudy

* #11 Add tests for EventStudyFHS

* #11 Add stata results for comparison

* #11 Add df_EventStudyFHS_example and fix df_EventStudyOLS_example

* #11 Update documentation

* #11 Update examples

* #11 Make example lines fewer than 100 characters for check()

* #11 Make invoking FHS logic explicit

* #11 Add tests for proxy IV selection

* #11 Edit proxyIV selection message

* #11 Add FHS example to PreparePlottingData()

* #11 Add FHS example to EventStudyPlot()

* Add unit tests for PreparePlottingData #11

I copied all of the unit tests that we used for the OLS case since we
want all of those conditions to also hold for FHS. I added one
additional test to check that the proxyIV variable has y-value = 0.

* #11 Fix copy-paste error

* Add unit tests for EventStudy() #11

I copied all of the unit tests that we used for the OLS case since we
want all of those conditions to also hold for FHS.

* Add unit tests for EventStudyPlot() #11

I copied all of the unit tests that we used for the OLS case since we
want all of those conditions to also hold for FHS.

* Remove EventStudy() tests that don't make sense for FHS #11

* Change OLS/FHS section delimiter #11

The new delimiter makes the OLS and FHS sections show up in the script
outline (Ctrl + Shift + O) and makes it easier to navigate.

* #11 Specify dplyr as namespace for setdiff

* #11 Adding FHS tests for AddCI

* #11 Adding SuptBand test for FHS

* #11 Implement anticipatory effects normalization

* #11 Add unit test for anticipation effects logic

* #11 #12 Add default number of suptband simulations to documentation

* #11 #12 Uncomment GitHub Actions yaml

* Revert "#11 #12 Uncomment GitHub Actions yaml"

This reverts commit 85be70af3f82b99a55c7da703ea3ec86de5a2cbf.

* #11 Rewrite if-else statement

Co-authored-by: Nathan Schor <70981003+nateschor@users.noreply.github.com>

* #11 Remove redundant line

* #11 Relocate stopping condition

* #11 Break grepl regex into two lines

* #11 Dropping extraneous function from development

* #11 Correcting for second note from check()

* #11 Removing warning by adding data documentation

* #11 Removing first set of notes

* #11 Remove string to class comparisons

* #12 Improved fix for "binding" note

* #11 #12 update default_override logic

Co-authored-by: Richard Calvo <97416734+rcalvo12@users.noreply.github.com>

* #11 #12 update default_override documentation language

Co-authored-by: Richard Calvo <97416734+rcalvo12@users.noreply.github.com>

* #11 #12 Update default_override warning message

* #11 #12 Resolve rlang warning

* #11 Fixing formatting of documentation

* #11 #12 Fix documentation formatting

* #11 #12 Update anticipation effects message

* #11 #12 Remove redundant rlang

* #11 #12 Incorporate changes to anticipation effects argument

* #11 Fix normalization for pre-trends test comparison

* #11 Changing syntax to simpler format

* #11 Running full set of tests

* Experiment with R version for #11

* Disables workflow for #11

Co-authored-by: ew487 <108754119+ew487@users.noreply.github.com>
Co-authored-by: Richard Calvo <97416734+rcalvo12@users.noreply.github.com>
Co-authored-by: jmshapir <jesse.m.shapiro@gmail.com>

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -8,54 +8,54 @@ on:
 name: R-CMD-check
 
 jobs:
-  simple-task:
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
-    steps:
-      - name: simple-step
-        run: echo "When you want to run real tests, uncomment R-CMD-check, comment out simple-task"
+   simple-task:
+     timeout-minutes: 1
+     runs-on: ubuntu-latest
+     steps:
+       - name: simple-step
+         run: echo "When you want to run real tests, uncomment R-CMD-check, comment out simple-task"
 
-#   R-CMD-check:
-#     timeout-minutes: 10
-#     runs-on: ${{ matrix.config.os }}
-#
-#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
-#
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         config:
-#           - {os: ubuntu-latest,   r: 'release'}
-#
-#     env:
-#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-#       R_KEEP_PKG_SOURCE: yes
-#
-#     steps:
-#       - uses: actions/checkout@v2
-#
-#       - uses: r-lib/actions/setup-pandoc@v1
-#
-#       - uses: r-lib/actions/setup-r@v1
-#         with:
-#           r-version: ${{ matrix.config.r }}
-#           http-user-agent: ${{ matrix.config.http-user-agent }}
-#           use-public-rspm: true
-#
-#       - uses: r-lib/actions/setup-r-dependencies@v1
-#         with:
-#           extra-packages: rcmdcheck
-#
-#       - uses: r-lib/actions/check-r-package@v1
-#
-#       - name: Show testthat output
-#         if: always()
-#         run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-#         shell: bash
-#
-#       - name: Upload check results
-#         if: failure()
-#         uses: actions/upload-artifact@main
-#         with:
-#           name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-#           path: check
+  # R-CMD-check:
+  #   timeout-minutes: 10
+  #   runs-on: ${{ matrix.config.os }}
+
+  #   name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       config:
+  #         - {os: ubuntu-latest,   r: 'release'}
+
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     R_KEEP_PKG_SOURCE: yes
+
+  #   steps:
+  #     - uses: actions/checkout@v2
+
+  #     - uses: r-lib/actions/setup-pandoc@v1
+
+  #     - uses: r-lib/actions/setup-r@v1
+  #       with:
+  #         r-version: ${{ matrix.config.r }}
+  #         http-user-agent: ${{ matrix.config.http-user-agent }}
+  #         use-public-rspm: true
+
+  #     - uses: r-lib/actions/setup-r-dependencies@v1
+  #       with:
+  #         extra-packages: rcmdcheck
+
+  #     - uses: r-lib/actions/check-r-package@v1
+
+  #     - name: Show testthat output
+  #       if: always()
+  #       run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+  #       shell: bash
+
+  #     - name: Upload check results
+  #       if: failure()
+  #       uses: actions/upload-artifact@main
+  #       with:
+  #         name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+  #         path: check
